### ISSUE TITLE
App uses default title + favicon

### ISSUE THREAD

**Issue by aaemnnosttv** [techanvil/zenhub-dependency-graph#51]
The app currently uses the default `<title>` and favicon from the React project scaffold so it's hard to find by just looking for the tab :)

**Comment by techanvil** [comment]
Thanks for raising this @aaemnnosttv, it's been bugging me a bit too. I've applied a quick fix, will take a closer look when I can!

**Comment by aaemnnosttv** [comment]
Thanks @techanvil ! I'll close this out now since I see the root issue has been addressed, although I'm sure it could be enhanced in the future by making the title dynamic for example. Thanks!

**Comment by techanvil** [comment]
Thanks @aaemnnosttv! Making the page title dynamic, say based on the selected epic, would be a nice enhancement. I have added it to the general TODO list :)
