### ISSUE TITLE
Feature Request: Highlight blocking and dependent issues on hover

### ISSUE THREAD

**Issue by nfmohit** [techanvil/zenhub-dependency-graph#60]
It would be nice to add an option to highlight blocking and dependent issues when an issue is hovered. This may be specially beneficial when looking at larger epics.

Happy to pick this up in the next hackathon.

**Comment by techanvil** [comment]
Thanks for the suggestion, @nfmohit! Sounds like a useful addition, please do go for it at the next Hackathon if you are so inclined :)
